name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test before release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Protocol Buffers compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test --all-features

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Protocol Buffers compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Ensure we get the full history for proper release notes
        fetch-depth: 0
        # Ensure clean checkout
        clean: true

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build release binaries
      run: |
        # Clean any previous builds to avoid conflicts
        cargo clean
        # Build with explicit target for consistency
        cargo build --release --bin runnx-runner
        # Verify the binary was created
        ls -la target/release/runnx-runner
        
    - name: Create release archive
      run: |
        mkdir -p artifacts
        # Copy binary
        cp target/release/runnx-runner artifacts/
        # Copy documentation and licenses
        cp README.md LICENSE-MIT LICENSE-APACHE artifacts/
        # Create archive from the artifacts directory only
        cd artifacts
        tar -czf ../runnx-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz *
        cd ..
        mv runnx-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz artifacts/
        
    - name: Verify release archive
      run: |
        # List archive contents to verify
        echo "Archive contents:"
        tar -tzf artifacts/runnx-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
        # Check archive size
        ls -lh artifacts/runnx-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz

    - name: Extract release notes
      id: extract-release-notes
      run: |
        # Extract release notes from CHANGELOG.md or create basic notes
        if [ -f CHANGELOG.md ]; then
          echo "Reading release notes from CHANGELOG.md"
          # This is a simple extraction - you might want to improve this
          awk '/^## \[/{if(found) exit; found=1; next} found' CHANGELOG.md > release_notes.txt
        else
          echo "Release ${{ github.ref_name }}" > release_notes.txt
          echo "" >> release_notes.txt
          echo "See [CHANGELOG.md](CHANGELOG.md) for details." >> release_notes.txt
        fi
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body_path: release_notes.txt
        files: artifacts/runnx-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
